name: Update to README

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  change-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update date to README.md
        run: |
          date = $(date "+%Y-%m-%d")
          echo $date
          sed 's/\x60((.|\n)*)\x60/\x60$date\x60/g' README.md
          git add README.md
          git commit -m "update: date
